<a href="https://colab.research.google.com/github/fatimazahrae561/Python_tps/blob/main/Correction_complete_s01_et_s02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importation de bibliothèques pour le calcul numérique et la manipulation de données
import numpy as np            # NumPy : pour les tableaux et opérations mathématiques vectorisées
import pandas as pd           # Pandas : pour la manipulation et l'analyse de données tabulaires (DataFrames)

# Importation pour sauvegarde et chargement de modèles
import pickle                 # Pickle : pour sérialiser et désérialiser les objets Python (ex : modèles entraînés)

# Importation pour prétraitement des données
from sklearn.preprocessing import LabelEncoder, StandardScaler
# LabelEncoder : pour convertir les variables catégorielles en valeurs numériques
# StandardScaler : pour normaliser les données numériques (moyenne = 0, écart-type = 1)

# Importation pour division des données
from sklearn.model_selection import train_test_split
# train_test_split : pour diviser les données en ensembles d'entraînement et de test

# Importation de l'algorithme K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
# KNeighborsClassifier : algorithme de classification basé sur les k voisins les plus proches

# Importation des métriques d'évaluation
from sklearn.metrics import confusion_matrix, accuracy_score
# confusion_matrix : matrice montrant les vrais positifs, faux positifs, vrais négatifs, faux négatifs
# accuracy_score : calcul de la précision globale du modèle

In [ ]:
# Lecture du fichier CSV contenant le dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
# pd.read_csv() : fonction de Pandas pour charger un fichier CSV dans un DataFrame
# 'Social_Network_Ads.csv' : le nom du fichier contenant les données
# dataset : variable qui stocke le DataFrame, représentant les données sous forme tabulaire

# Affichage des 5 premières lignes du dataset
dataset.head()
# head() : méthode de Pandas qui montre les premières lignes pour vérifier que les données sont correctement chargées
# utile pour examiner les colonnes, les types de données et quelques exemples de valeurs


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
# Encodage de la variable catégorielle 'Gender' en valeurs numériques
dataset['Gender'] = LabelEncoder().fit_transform(dataset['Gender'].astype(str))
# LabelEncoder() : transforme les catégories en nombres (ex: 'Male' → 1, 'Female' → 0)
# .astype(str) : assure que toutes les valeurs sont traitées comme des chaînes de caractères
# fit_transform() : apprend les catégories et les convertit en nombres en une seule étape
# On remplace la colonne 'Gender' originale par sa version numérique dans le DataFrame

# Sélection des variables indépendantes (features) et dépendante (target)
X = dataset[['Age', 'EstimatedSalary', 'Gender']].values
# X : tableau numpy contenant les colonnes 'Age', 'EstimatedSalary' et 'Gender'
# .values : convertit le DataFrame Pandas en tableau numpy pour l'utiliser avec scikit-learn
Y = dataset['Purchased'].values
# Y : tableau numpy contenant la variable cible 'Purchased' (0 ou 1)
# Cette variable sera utilisée pour entraîner le modèle à prédire si un utilisateur achète ou non


[[   19 19000     1]
 [   35 20000     1]
 [   26 43000     0]
 ...
 [   50 20000     0]
 [   36 33000     1]
 [   49 36000     0]]


In [ ]:
# Division du dataset en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=0)
# train_test_split : fonction de scikit-learn pour séparer les données en deux ensembles
# X : variables indépendantes (features)
# Y : variable dépendante (target)
# test_size=0.25 : 25% des données seront utilisées pour le test, 75% pour l'entraînement
# random_state=0 : fixe la "graine" du générateur aléatoire
#     -> permet de reproduire exactement le même mélange (shuffle) des données à chaque exécution
#     -> ne contrôle pas combien de fois les données sont brassées, mais rend le shuffle déterministe
# X_train, y_train : données et labels pour entraîner le modèle
# X_test, y_test : données et labels pour évaluer les performances du modèle sur des données inédites


# Explication de la graine

En programmation et machine learning, une “graine” (seed en anglais) est un nombre utilisé pour initialiser un générateur de nombres aléatoires.

💡 Plus précisément :

Les ordinateurs ne peuvent pas générer de vrais nombres aléatoires, ils créent des nombres pseudo-aléatoires avec un algorithme.

La graine sert de point de départ pour cet algorithme.

Si tu utilises la même graine, tu obtiendras toujours la même séquence de nombres pseudo-aléatoires.

Si tu changes la graine (ou que tu n’en mets pas), la séquence sera différente.

In [ ]:
# Création d'un objet StandardScaler pour normaliser les données
sc = StandardScaler()
# StandardScaler : outil de scikit-learn pour centrer et réduire les données
#     -> moyenne = 0, écart-type = 1 pour chaque feature
#     -> cela améliore les performances des algorithmes basés sur les distances (ex: KNN, SVM)

# Normalisation des données d'entraînement
X_train = sc.fit_transform(X_train)
# fit_transform() :
#     -> 'fit' calcule la moyenne et l'écart-type de chaque colonne sur les données d'entraînement
#     -> 'transform' applique la normalisation sur ces données
#     -> X_train devient un tableau numpy avec toutes les features centrées et réduites

# Normalisation des données de test
X_test = sc.transform(X_test)
# transform() uniquement : on applique la même normalisation que celle calculée sur X_train
#     -> important : on ne refait pas le fit sur le test, sinon on introduit une fuite de données (data leakage)
#     -> X_test est maintenant normalisé selon les mêmes paramètres que X_train


In [ ]:
# Création d'un modèle K-Nearest Neighbors (KNN)
knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
# KNeighborsClassifier : classe de scikit-learn pour la classification basée sur les k plus proches voisins
# n_neighbors=5 : le modèle va regarder les 5 voisins les plus proches pour faire la prédiction
# metric='minkowski' : type de distance utilisé pour calculer la proximité entre les points
# p=2 : paramètre pour la distance de Minkowski, p=2 correspond à la distance Euclidienne classique

# Entraînement du modèle sur les données d'entraînement
knn.fit(X_train, y_train)
# fit() : méthode qui "apprend" le modèle à partir des données
#     -> pour KNN, cela consiste à mémoriser toutes les données d'entraînement
#     -> les prédictions seront faites en comparant la distance entre un point test et ces données mémorisées

KNeighborsClassifier()

In [ ]:
# Prédiction des labels pour l'ensemble de test
y_pred = knn.predict(X_test)
# predict() : méthode qui utilise les k plus proches voisins de chaque échantillon de X_test
#     -> détermine la classe majoritaire parmi les voisins
# y_pred : tableau numpy contenant les prédictions pour chaque échantillon de test

# Calcul de la précision (accuracy) du modèle
accuracy = accuracy_score(y_test, y_pred)
# accuracy_score() : compare les labels réels (y_test) avec les prédictions (y_pred)
#     -> renvoie le pourcentage de prédictions correctes
# accuracy : valeur flottante entre 0 et 1 (ex: 0.92 → 92% correct)
print(y_test)
print(y_pred)
# Calcul de la matrice de confusion
cm = confusion_matrix(y_test, y_pred)
print(cm)
# confusion_matrix() : tableau 2x2 (pour classification binaire)
#     -> montre le nombre de vrais positifs (TP), faux positifs (FP),
#        vrais négatifs (TN) et faux négatifs (FN)
#     -> permet de comprendre où le modèle se trompe

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]
[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1]
[[64  4]
 [ 3 29]]


In [ ]:
accuracy

0.93

In [ ]:
# Sauvegarde du modèle KNN entraîné dans un fichier pour une utilisation future
with open('knn_model.pkl', 'wb') as file:
    # 'knn_model.pkl' : nom du fichier où le modèle sera stocké
    # 'wb' : mode écriture binaire, nécessaire pour pickle
    pickle.dump(knn, file)
    # pickle.dump(obj, file) : sérialise l'objet Python (ici, le modèle KNN)
    #     -> l'objet est converti en format binaire et enregistré dans le fichier
    #     -> permet de charger plus tard le modèle sans le réentraîner


In [ ]:
# Chargement du modèle KNN sauvegardé
with open('knn_model.pkl', 'rb') as file:
    model = pickle.load(file)

# Exemple de nouveaux utilisateurs
# ⚠️ Important : respecter l'ordre des colonnes exact X = ['Age', 'EstimatedSalary', 'Gender']
nouvelles_donnees = pd.DataFrame([
    {'Age': 25, 'EstimatedSalary': 35000, 'Gender': 1},
    {'Age': 45, 'EstimatedSalary': 85000, 'Gender': 1},
    {'Age': 29, 'EstimatedSalary': 120000, 'Gender': 1}
])

# Normalisation selon le même scaler utilisé pour l'entraînement
# ⚠️ Warning courant :
# "X has feature names, but StandardScaler was fitted without feature names"
# Sens : le scaler a été entraîné (fit) sur un numpy array sans noms de colonnes.
#        Maintenant, on lui passe un DataFrame avec noms de colonnes.
#        Le warning indique que les noms de colonnes ne correspondent pas à ce qu'il a vu lors du fit.
#        Les valeurs sont quand même normalisées correctement si l'ordre des colonnes est respecté.
# Solution : transformer le DataFrame en numpy array avant le transform pour supprimer le warning.
nouvelles_donnees_scaled = sc.transform(nouvelles_donnees.values)

# Prédiction
predictions = model.predict(nouvelles_donnees_scaled)

# Ajout des prédictions dans le DataFrame avec une présentation lisible
nouvelles_donnees['Prediction'] = [
    '🛒 Purchased' if p == 1 else '🚫 Not Purchased' for p in predictions
]

# Affichage des résultats
nouvelles_donnees

Age  EstimatedSalary  Gender       Prediction
0   25            35000       1  🚫 Not Purchased
1   45            85000       1      🛒 Purchased
2   29           120000       1      🛒 Purchased

In [ ]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd

# -------------------------------
# 1. Création des widgets pour la saisie
# -------------------------------

# Slider pour sélectionner l'âge de l'utilisateur
age = widgets.IntSlider(
    value=30,      # valeur initiale
    min=18,        # âge minimum
    max=60,        # âge maximum
    step=1,        # incréments de 1
    description="Age:"  # étiquette visible pour l'utilisateur
)

# Slider pour sélectionner le salaire estimé
salary = widgets.IntSlider(
    value=50000,      # valeur initiale
    min=10000,        # salaire minimum
    max=150000,       # salaire maximum
    step=5000,        # incréments de 5000
    description="Salary:"  # étiquette visible
)

# Dropdown pour sélectionner le genre
gender = widgets.Dropdown(
    options=[("Female", 0), ("Male", 1)],  # valeurs utilisées par le modèle (0 ou 1)
    description="Gender:"                  # étiquette visible
)

# Bouton pour lancer la prédiction
predict_button = widgets.Button(
    description="Predict",  # texte sur le bouton
    button_style='success', # style vert
    icon='check'            # icône de validation
)

# Zone de sortie pour afficher les résultats et messages
output = widgets.Output()

# -------------------------------
# 2. Fonction de prédiction
# -------------------------------
def on_predict_clicked(b):
    """
    Cette fonction est appelée lorsqu'on clique sur le bouton "Predict".
    Elle prend les valeurs des widgets, les normalise et effectue une prédiction avec le modèle KNN.
    """
    with output:
        clear_output()  # Efface la sortie précédente pour ne pas empiler les résultats

        # Créer un DataFrame avec les entrées de l'utilisateur
        # ⚠️ Très important : respecter exactement l'ordre des colonnes utilisé pour entraîner le modèle
        # X = ['Age','EstimatedSalary','Gender']
        data = pd.DataFrame([{
            'Age': age.value,
            'EstimatedSalary': salary.value,
            'Gender': gender.value
        }])

        # Normaliser les données avec le StandardScaler déjà entraîné
        # ⚠️ UserWarning fréquent : "X has feature names, but StandardScaler was fitted without feature names"
        # Cela se produit parce que le scaler a été entraîné sur un numpy array (sans noms de colonnes)
        # et maintenant on lui passe un DataFrame (avec noms de colonnes)
        # La solution : utiliser data.values pour passer un numpy array et supprimer le warning
        data_scaled = sc.transform(data.values)

        # Faire la prédiction avec le modèle KNN chargé
        pred = model.predict(data_scaled)[0]

        # Convertir la prédiction 0/1 en texte lisible pour l'utilisateur avec emoji
        result = "🛒 Purchased" if pred == 1 else "🚫 Not Purchased"

        # Afficher le résultat de la prédiction
        print(f"Prediction result: {result}")

        # Afficher également les données saisies pour vérification
        display(data)

# -------------------------------
# 3. Lier le bouton à la fonction
# -------------------------------
# Quand l'utilisateur clique sur le bouton, la fonction on_predict_clicked est exécutée
predict_button.on_click(on_predict_clicked)

# -------------------------------
# 4. Affichage des widgets
# -------------------------------
# Les widgets sont affichés dans l'ordre : âge, salaire, genre, bouton, zone de sortie
display(age, salary, gender, predict_button, output)


IntSlider(value=30, description='Age:', max=60, min=18)

IntSlider(value=50000, description='Salary:', max=150000, min=10000, step=5000)

Dropdown(description='Gender:', options=(('Female', 0), ('Male', 1)), value=0)

Button(button_style='success', description='Predict', icon='check', style=ButtonStyle())

Output()